### PR TITLE
27 Additional Guns

### PR DESCRIPTION
**Pull request by Hobbeswyn**
**27 Additional Guns:**

Maxim 9:
maxim_9

G11:
G11
G112

RBB Lazer Rifle:
crossbow
crossbow2

AA12:
AA12 Shotgun

AWP:
AWP

Barrett M95:
Barrett M95

Deagle:
Deagle

DP-27:
DP-27

M1 Garand:
Garand

M41A1 Aliens Pulse Rifle:
M41A1 Aliens Pulse Rifle

Rust Double Barrel Shotgun:
Rust Double Barrel Shotgun

Rust Eoka Pistol:
Rust Eoka bbmodel

Rust M92 Pistol:
Rust M92 Pistol

Rust M249 Machine Gun:
Rust M249

Rust M2492

Tavor CTAR 21:
ctar21

Rust Thompson Submachine Gun:
Rust Thompson

Rust SMG:
RUST SMG

Rust Semi-Auto Pistol:
Rust Semi-Auto Pistol

Rust Semi-Auto Rifle:
Rust Semi Auto Rifle

Rust Revolver:
Revolver

Rust MP5a4:
Rust MP5a4

Drakon:
bow

Mossberg O/U:
mossbergou

### CODE REVIEW

**Comment by AlbusRexII** [comment]
Glad to see you're still bringing these awesome models to life! If you're using my handheld code and changes then remember to credit me for them. :)

**Comment by Hobbeswyn** [comment]
> Glad to see you're still bringing these awesome models to life! If you're using my handheld code and changes then remember to credit me for them. :)

I stopped working with you due to your shitty sexist comments. Screw off with your fake smile and take it someplace else. I've told you to stop harassing me, but apparently you can't seem to get a message.

**Comment by Igggosha** [comment]
Hello, everyone involved. I am interested in getting to know more about the situation and what were the "sexist comments" mentioned here. Could someone please tell me some background for this situation?

**Comment by Autovw** [comment]
I'm sorry for having to lock the conversation, but this is definitely not the place for this. Please keep conversations on our GitHub productive, if there's issues someone wants to talk about, reach out to me on Discord.

**Pull request closed without merging**
